name: scimet
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.8
  firebase_core: ^2.27.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.3
  page_flip: ^0.2.3
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.13.1
  tutorial_coach_mark: ^1.2.11
  pdfrx: ^1.0.84
  shadcn_ui: ^0.14.1
  google_fonts: ^6.2.1
  uuid: ^4.5.1
  onboarding: ^4.0.2
  introduction_screen: ^3.1.14
  connectivity_plus: ^6.1.0
  rename_app: ^1.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/images/module_1/plants/
    - assets/images/module_1/animals/
    - assets/images/module_2/
    - assets/images/module_3/
    - assets/images/module_4/
    - assets/images/module_5/
    - assets/images/quiz/mod2/
    - assets/images/quiz/mod3/
    - assets/images/quiz/mod4/
    - assets/images/quiz/mod5/
    - assets/images/quiz/mod6/
    - assets/contents/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600