// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYJ35nd4vVB9nAm11OJ_w7orJ8NxolArw',
    appId: '1:264825109099:web:8b2e8a779d8893de3a0f2e',
    messagingSenderId: '264825109099',
    projectId: 'scimet-34e53',
    authDomain: 'scimet-34e53.firebaseapp.com',
    storageBucket: 'scimet-34e53.appspot.com',
    measurementId: 'G-5QCPNDGKYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5TWUbxBJ_jMraPtP83Y21q4iBOfcqhIk',
    appId: '1:264825109099:android:d1e6ea39f9ef54953a0f2e',
    messagingSenderId: '264825109099',
    projectId: 'scimet-34e53',
    storageBucket: 'scimet-34e53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH-Ax7uGJHqZ1QDOspjz2bTi6QkQrCMNI',
    appId: '1:264825109099:ios:36bb8fedd50cf1373a0f2e',
    messagingSenderId: '264825109099',
    projectId: 'scimet-34e53',
    storageBucket: 'scimet-34e53.appspot.com',
    iosBundleId: 'com.example.scimet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH-Ax7uGJHqZ1QDOspjz2bTi6QkQrCMNI',
    appId: '1:264825109099:ios:36bb8fedd50cf1373a0f2e',
    messagingSenderId: '264825109099',
    projectId: 'scimet-34e53',
    storageBucket: 'scimet-34e53.appspot.com',
    iosBundleId: 'com.example.scimet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYJ35nd4vVB9nAm11OJ_w7orJ8NxolArw',
    appId: '1:264825109099:web:924b89cc19d51abb3a0f2e',
    messagingSenderId: '264825109099',
    projectId: 'scimet-34e53',
    authDomain: 'scimet-34e53.firebaseapp.com',
    storageBucket: 'scimet-34e53.appspot.com',
    measurementId: 'G-XK3ZFNKWKC',
  );
}
